---
# This is my very first Ansible Playbook

- name: This is my very first Ansible Playbook
  hosts: debian:centos

  tasks:
  - name: Testing connection with hosts
    ping: 

  - name: Test shell quoting
    command: /bin/echo $HOME
    remote_user: root
...
