---
- name: Using loops to do stuff
  hosts: debian:centos

  tasks: 
    - name: The most basic loop
      user:
        name: "{{ item }}"
        state: absent
      loop:
        - John
        - Doe

    - name: create some groups
      group:
        name: "{{ item }}"
        state: present
      loop:
        - a_group
        - b_group

    - name: creating a few users and groups
      user:
        name: "{{ item.name }}"
        group: "{{ item.group }}"
        state: present
      loop:
        - { name: 'a_user', group: 'a_group' }
        - { name: 'b_user', group: 'b_group' }

    - name: Using do until loops
      command: /bin/echo "Found you"
      register: resposta
      until: resposta.stdout.find("Found ya") == -1
      retries: 4
      delay: 4

    - name: Looping over our inventory, just print the host name
      command: /bin/echo {{ item }}
      # where group[var], 'var' is the group name on hosts file, such a debian or centos
      loop: "{{ groups['all'] }}"

    - name: Looping over the current host list
      debug:
        msg: The host is {{ item }}
      loop: "{{ ansible_play_batch }}"
...
