---
- name: Privilege Escalation
  hosts: centos:debian

  tasks:
  - name: Create user 'Hulk'
    user:
      name: Hulk
      home: /home/hulk
      state: present
    become: yes
    become_method: su
...
