---
- name: Install PHP, Apache and Git
  yum:
    name: ['php', 'httpd', 'php-mysql', 'git']
    state: latest

- name: Start Apache
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: Deploy code from Git repo
  git:
    repo: "{{ repo }}"
    dest: /var/www/html
    version: HEAD
...
